### ISSUE TITLE
Headers already sent - Issue and Fix (Theme related)

### ISSUE THREAD

**Issue by boegi** [danielpowney/my-chatbot#13]
With the last version I got an Error...
Warning: Cannot modify header information - headers already sent by (output started at /www/htd...ad/wp-content/themes/magxp-by-mythemeshop/header.php:1) in /www/htd...ad/wp-content/plugins/my-chatbot/includes/scripts.php on line 42

I fixed it with the following change in the file script.php (Of the Plugin)

New:
add_action( 'send_headers', 'myc_load_scripts' );
Old:
//add_action( 'wp_enqueue_scripts', 'myc_load_scripts' );

I'm not deep in Web/WP coding so please check again, if this is the right way to call the function with a cookie. For me it worked. 

BTW. Thanks for the wonderful Plugin!

**Comment by danielpowney** [comment]
Thanks for this. I'll need to move where the cookie is set so that it happens before the HTML appears.

**Comment by danielpowney** [comment]
Fixed. Please find changes in develop branch for v0.5 updates. https://github.com/danielpowney/my-chatbot/commit/524447f828f3b2a4ee5d7500753ad9bc7465296f

**Comment by boegi** [comment]
Perfect...
Wonderful Plugin... But i already told you ;-)

Thanks and have a nice weekend!
