### ISSUE TITLE
Allow the plugin to make calls to the Dialogflow API specifying languages other than English

### ISSUE THREAD

**Issue by wellingtonsampaio** [danielpowney/my-chatbot#21]
Currently HTTP requests to the Dialogflow API always set the "**lang**" to "**en**" making it work with agents in English only.

Since Dialogflow supports multiple languages and to start a conversation in another language simply means setting the desired language on the HTTP call, would be good if the plugin could retrieve the current selected language of the WordPress site (when working with https://wpml.org/ for instance) and send it as part of the call.

**Comment by danielpowney** [comment]
Hi, v0.6 in the develop branch now supports choosing a different language. The language setting can be overwritten using the myc_language() filter too if needed. I will look at translating WordPress language slugs to Dialogflow language tags. So if you don't select a language it will use the current locale and work it out. This would allow it to work nicely with WPML. Cheers, Daniel

**Comment by danielpowney** [comment]
I've done that now :) Please try it out.
