### ISSUE TITLE
Set chat language

### ISSUE THREAD

**Issue by arinconc** [danielpowney/my-chatbot#24]
Hi!
I am testing the plugin but I do not know how I can set the language of the chatbot. Is there any way in which the browser language is detected and chatbot requests are made with the appropriate lang?

Thanks in advance,
Antonio

**Comment by danielpowney** [comment]
Hi Antonio,

Try the codebase in the develop branch. You can select the language in the plugin settings, or let it choose an appropriate langiage based on your locale. Note that Dialogflow does not support all languages.

Daniel

**Comment by arinconc** [comment]
Perfect Daniel!!
Thanks

Antonio

**Comment by sborar** [comment]
Hi Daniel,
Can the plugin find out the locale of the website and use it to set the locale of the chatbot automatically?

Thanks in advance,
Sheetal
