### ISSUE TITLE
Unimpressive View

### ISSUE THREAD

**Issue by muhammadyou** [danielpowney/my-chatbot#27]
I am using slack integration and the view doesn't look as good as provided in the screenshots. Kindly assist

**Comment by danielpowney** [comment]
Hi there,

Can you please attach screenshots?

Thanks,
Daniel

**Comment by muhammadyou** [comment]
![capture](https://user-images.githubusercontent.com/8754128/38202485-ead30736-36ac-11e8-8165-81c29e391fd0.PNG)
The quick links or buttons look ugly. Also, there is no support for cards, so I cannot create a carousel. Appreciate if you can create view for all kinds of rich messages

**Comment by muhammadyou** [comment]
or How can i customize the view like use Materialize?

**Comment by danielpowney** [comment]
The buttons inherit your theme styles. You can customize the style using CSS.
