### ISSUE TITLE
Wrong label for german locale

### ISSUE THREAD

**Issue by samuelsouque** [danielpowney/my-chatbot#33]
Hello,

Thank you for your work on this plugin!
I just wanted to state a tiny issue which impact the ability of Dialogflow to answer to an intent in German.
In the file includes/scripts.php, at line 187, the corresponding value for the locale "de-DE" should be "de" and not "gr".
Would it be possible for you to commit this minor fix?
Thank you in advance.

Best regards,
Samuel

**Comment by danielpowney** [comment]
Added
