### ISSUE TITLE
Dialogflow API v1 will soon be deprecated

### ISSUE THREAD

**Issue by sbelitz** [danielpowney/my-chatbot#36]
The plugin is currently using Dialogflow API v1, wich will be deprecated on October 23, 2019:
https://dialogflow.com/docs/reference/v1-v2-migration-guide

Any plans to update the plugin to API v2?

Many thanks, good work Daniel.

**Comment by JoukeD** [comment]
Hi Daniel,

Thank you for such a great plugin!

Regarding the issue from @sbelitz , are you considering updating the plugin to the new Dialogflow API v2?

If you cannot find the time i'll be willing to help out 👍 

Thank you in advance!

**Comment by danielpowney** [comment]
Hi @JoukeD . I haven't had time to update it. Would love your help to update it. Cheers,

**Comment by lucguerraz** [comment]
Hello, will this be done soon? If you are interested I would be willing to help out.

Thanks a lot 😀

**Comment by danielpowney** [comment]
I've updated the plugin to support Dialogflow v2 :)
